# Generated by Django 2.0.7 on 2018-11-07 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('event', models.CharField(max_length=20, verbose_name='事件')),
                ('describe', models.CharField(default='无', max_length=100, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('achieve', models.BooleanField(default=True, verbose_name='是否生效')),
                ('importance', models.IntegerField(default=0, verbose_name='重要性')),
                ('flag', models.IntegerField(choices=[(0, 'none'), (1, 'red'), (2, 'yellow'), (3, 'blue'), (4, 'green')], default=0, verbose_name='旗子标记')),
                ('remind_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提醒时间')),
                ('remark', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': '代办清单',
                'verbose_name_plural': '代办清单',
            },
        ),
    ]
