# Generated by Django 2.0.7 on 2018-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181107_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='describe',
            field=models.CharField(blank=True, default='无', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='remark',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
    ]
